[build-system]
requires = ["setuptools>=42", "setuptools_scm>=8", "wheel"]
build-backend = "setuptools.build_meta"

[project]
authors = [{name = "Lucas Faudman", email = "lucasfaudman@gmail.com"}]
dynamic = ["classifiers"]
name = "apkscan"
version = "0.4.0"
requires-python = ">=3.10"
readme = "README.md"
license = { file = "LICENSE" }
description = "Scan for secrets, endpoints, and other sensitive data after decompiling and deobfuscating Android files. (.apk, .xapk, .dex, .jar, .class, .smali, .zip, .aar, .arsc, .aab, .jadx.kts)"
keywords = [
    "secret scanner", "jadx", "decompile", "android", "java", "security", "mobile", "decompiler",
    "concurrency", "penetration-testing", "apktool", "security-tools", "fernflower", "cfr",
    "procyon", "enjarify", "krakatau", "secret-scanning", "decompiler-java", "secret-scanner",
    "apk", "xapk", "dex", "jar", "class", "smali", "zip", "aar", "arsc", "aab", "jadx.kts"
]
dependencies = [
    "enjarify-adapter",
    "pyyaml",
    "toml",
]

[project.urls]
Homepage = "https://github.com/LucasFaudman/apkscan.git"
Repository = "https://github.com/LucasFaudman/apkscan.git"

[project.scripts]
apkscan = "apkscan.main:main"

[project.optional-dependencies]
mypyc = ["mypy[mypyc]", "mypy_extensions"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["LICENSE"]
"apkscan.secret_locators" = ["*.json", "*.yaml", "*.yml", "*.toml"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/apkscan/_version.py"

[tool.black]
line-length = 120
exclude = "src/apkscan/main.py"
force-exclude = "src/apkscan/main.py"
